services:
  neo4j:
    image: neo4j:5
    environment:
      NEO4J_AUTH: neo4j/smarthr123
      NEO4J_PLUGINS: '["apoc"]'
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - neo4jdata:/data

volumes:
  neo4jdata:
