spring:
  application:
    name: SmartHR Assistant

  ai:
    ollama:
      base-url: http://localhost:11434
      chat:
        options:
          model: llama3.2 # or llama3.2, phi3:mini, gemma2 ,mistral
          # 0.0 = precise/deterministic, 1.0 = creative
          temperature: 0.3

server:
  port: 8080
