spring:
  application:
    name: SmartHR Assistant

  ai:
    ollama:
      base-url: http://localhost:11434
      chat:
        num-predict: 500
        temperature: 0.3
        model: llama3.2
      embedding:
        options:
          model: nomic-embed-text

server:
  port: 8080
